Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Example demonstrating the usage of particle distribution strategies

# Assuming necessary imports
import numpy as np
from particula.base.particle import (
    create_particle_strategy,
    Particle,
    MassBasedStrategy,
    RadiiBasedStrategy,
    SpeciatedMassStrategy,
)

# Creating particle distribution examples
mass_distribution = np.array([100, 200, 300], dtype=np.float64)
density = np.float64(2.5)
concentration = np.array([10, 20, 30], dtype=np.float64)

# Instantiate a particle strategy
mass_based_strategy = MassBasedStrategy()

# Create a Particle instance using the MassBasedStrategy
particle = Particle(strategy=mass_based_strategy,
                    distribution=mass_distribution,
                    density=density,
                    concentration=concentration)

# Accessing calculated properties
print("Mass of particles:", particle.get_mass())
print("Radius of particles:", particle.get_radius())
print("Total mass of the particle distribution:", particle.get_total_mass())
------------------


Traceback [0;36m(most recent call last)[0m:

[0m  File [1;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3577[0m in [1;35mrun_code[0m
    exec(code_obj, self.user_global_ns, self.user_ns)[0m

[0m  Cell [1;32mIn[1], line 5[0m
    from particula.base.particle import ([0m

[0;36m  File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/particula/__init__.py:18[0;36m
[0;31m    from particula.logger_setup import setup[0;36m

[0;36m  File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/particula/logger_setup.py:62[0;36m[0m
[0;31m    logging_dir = "logging"[0m
[0m    ^[0m
[0;31mSyntaxError[0m[0;31m:[0m expected 'except' or 'finally' block


